[package]
name = "eipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.5"
syscalls = { version = "0.6", default-features = false }
nix = "0.25.0"
